### ISSUE TITLE
change default branch from master to gh-pages, and remove master branch

### ISSUE THREAD

**Issue by vorburger** [alfio-event/alf.io-website#4]
This repo would be slightly easier to contribute to if in GitHub's Settings you would change the default branch from master to gh-pages, and remove master branch. Just a thought.

**Comment by cbellone** [comment]
That's a great suggestion, thanks!
I've updated the default branch to "gh-pages"

**Comment by vorburger** [comment]
@cbellone do you also want to delete the master branch? GitHub doesn't let you when it's the default, but after you change it you shold be able to, and IMHO it helps a bit to clarify this repo.
